spring.application.name=Z-fighters
spring.datasource.url=jdbc:postgresql://localhost:5432/z_fighters
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Spring MVC
server.port=9898